### Boolean Indexing

In [2]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [3]:
data = np.random.randn(7,4)

In [5]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [7]:
data[data>1] # for retreiving exact values

array([1.53991336, 2.30724388, 1.09858097, 1.03439889, 1.12157329,
       2.1237119 ])

In [8]:
data>1

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True, False, False, False],
       [ True, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False]])

In [9]:
data[names=="Bob"]

array([[ 0.0808026 , -1.67048104,  0.55825019, -0.05073677],
       [ 1.09858097, -0.88623252, -0.38034277,  0.75529835]])

In [10]:
data

array([[ 0.0808026 , -1.67048104,  0.55825019, -0.05073677],
       [ 0.61629979, -1.48100293, -0.00791499, -0.22264864],
       [-2.15662315,  0.38972853,  1.53991336,  2.30724388],
       [ 1.09858097, -0.88623252, -0.38034277,  0.75529835],
       [ 1.03439889, -0.72624286,  0.87186435,  1.12157329],
       [-1.6338198 ,  0.13174322, -1.09896629,  2.1237119 ],
       [ 0.93035643, -0.95613946,  0.87556702, -1.24047939]])

In [12]:
print(names=="Bob")

[ True False False  True False False False]


In [13]:
data[True, False, False, False, False, True]

array([], shape=(0, 7, 4), dtype=float64)

In [15]:
bol = np.array([True, False, False, False, False, True, False])
data[bol]

array([[ 0.0808026 , -1.67048104,  0.55825019, -0.05073677],
       [-1.6338198 ,  0.13174322, -1.09896629,  2.1237119 ]])

In [16]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [21]:
condition = names != "Bob"

In [22]:
data[~condition]

array([[ 0.0808026 , -1.67048104,  0.55825019, -0.05073677],
       [ 1.09858097, -0.88623252, -0.38034277,  0.75529835]])

In [23]:
data

array([[ 0.0808026 , -1.67048104,  0.55825019, -0.05073677],
       [ 0.61629979, -1.48100293, -0.00791499, -0.22264864],
       [-2.15662315,  0.38972853,  1.53991336,  2.30724388],
       [ 1.09858097, -0.88623252, -0.38034277,  0.75529835],
       [ 1.03439889, -0.72624286,  0.87186435,  1.12157329],
       [-1.6338198 ,  0.13174322, -1.09896629,  2.1237119 ],
       [ 0.93035643, -0.95613946,  0.87556702, -1.24047939]])

In [26]:
data[condition, 1:3]

array([[-1.48100293, -0.00791499],
       [ 0.38972853,  1.53991336],
       [-0.72624286,  0.87186435],
       [ 0.13174322, -1.09896629],
       [-0.95613946,  0.87556702]])

In [29]:
data = np.arange(28).reshape(7,4)
print(data)
print(condition)
data[condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 5,  6],
       [ 9, 10],
       [17, 18],
       [21, 22],
       [25, 26]])

In [31]:
data = np.arange(28).reshape(7,4)
print(data)
print(condition)
data[~condition,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
[False  True  True False  True  True  True]


array([[ 1,  2],
       [13, 14]])

In [32]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [33]:
cond = (names=="Bob") & (names=="Joe")
cond

array([False, False, False, False, False, False, False])

In [34]:
cond = (names=="Bob") | (names=="Joe")
cond

array([ True,  True, False,  True, False,  True,  True])

In [35]:
data[cond]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

### Fancy Indexing(for 2D):

In [36]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [44]:
arr[[4,0,1,7],[2,1,3,0]] 
#making orderpair by joining both matrices
#(4,2)(0,1)(1,3)(7,0)

array([4., 0., 1., 7.])

In [45]:
arr = np.arange(32).reshape(8,4)
print(arr)
arr[[1,5,7,2]][:,[0,3,1,2]]
#1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2]
#(1,0)(1,3)(1,1)(1,2)()()()()()()()()()()()(2,2)....

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [47]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [48]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [49]:
a = [22,33,44,55,77,55,44,22,11]
a

[22, 33, 44, 55, 77, 55, 44, 22, 11]

In [50]:
st = set()
st

{11, 22, 33, 44, 55, 77}

In [51]:
#vertically increase no of rows increase when axis is zero vive versa

In [53]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [54]:
np.vsplit(arr, 3)
#np.hsplit()

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [55]:
#jb vertical split kahee ga too churii horizontal pherni hai ik line ya tower bnaa lo matrix ko

In [56]:
np.hsplit(arr, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]