In [3]:
import numpy as np
my_array = np.array([[1,2,3,4],[4,4,5,5]])
my_array

array([[1, 2, 3, 4],
       [4, 4, 5, 5]])

In [5]:
my_second_array = np.asarray([1,2,3,3,4])
my_second_array

array([1, 2, 3, 3, 4])

In [7]:
myArray = np.arange(10)
myArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
myArray = np.ones((2,3))
myArray

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
myArray = np.ones_like(my_array)
myArray

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
myArray = np.empty((2,1))
myArray

array([[6.4113076e-317],
       [4.9406565e-324]])

In [9]:
import numpy as np
emp = np.empty((2,2))
myArray = np.full((3,3),12)
myArray

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [13]:
my2 = np.full_like(myArray,13)
my2

array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

In [18]:
my3 = np.eye(5,5)
my3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Data Types For ndarrays:

In [19]:
#You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [20]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [21]:
arr = np.array([3.7,-1.7,-2.6,0.5,12.9,10.1])
arr

array([ 3.7, -1.7, -2.6,  0.5, 12.9, 10.1])

In [23]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [24]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [27]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
#Calling astype always creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

## Arithmetic with NumPy Arrays

In [29]:
#Any arithmetic operations between equal-size arrays applies the operation element-wise:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [30]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [31]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [34]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [35]:
#Comparisons between arrays of the same size yield boolean arrays:
arr2>arr
#Operations between differently sized arrays is called broadcasting

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing:

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

In [41]:
arr_slice = arr[5:8]
arr_slice

array([0, 0, 0])

In [42]:
arr_slice[0] = 12345
arr

array([    0,     1,     2,     3,     4, 12345,     0,     0,     8,
           9])

In [44]:
#The “bare” slice [:] will assign to all values in an array:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [3]:
import numpy as np
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2]

array([7, 8, 9])

In [4]:
arr2d[0][2]

3

In [5]:
#for 2d array think of axis 0 as the “rows” of the array and axis 1 as the “columns.”
#In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions.
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#2 x 2 x 3 array
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
arr3d[0]#2 x 3 array

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d[0] = old_values

In [11]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
arr3d[1,0]

array([7, 8, 9])

### Broadcasting

In [16]:
x = np.array([[1,2,3]])
print(x.shape)
y = np.array([[4],[5]])
print(y.shape)

(1, 3)
(2, 1)


In [17]:
x,y = np.broadcast_arrays(x, y)
x

array([[1, 2, 3],
       [1, 2, 3]])

In [18]:
y

array([[4, 4, 4],
       [5, 5, 5]])

In [19]:
x+y

array([[5, 6, 7],
       [6, 7, 8]])