In [11]:
a = [1,2,3,4,5,6,7,8]
a

[1, 2, 3, 4, 5, 6, 7, 8]

In [12]:
%time
b=[]
for num in a:
    b.append(num*5)

Wall time: 0 ns


In [13]:
import numpy as np

In [15]:
%time
a = np.array([1,2,3,4,5,6,7,8,9])

Wall time: 0 ns


In [16]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [17]:
numpyArray = np.array([22,33,44.5,66], dtype = np.int8)
numpyArray

array([22, 33, 44, 66], dtype=int8)

In [18]:
numpyArray = np.array([22,33,44.5,66])
numpyArray

array([22. , 33. , 44.5, 66. ])

In [20]:
numpyArray = np.array([22,33,44.5,66], dtype = np.int8)
print(type(numpyArray))
numpyArray

<class 'numpy.ndarray'>


array([22, 33, 44, 66], dtype=int8)

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 85 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 4.87 s


In [5]:
randomArray = np.random.randn(3)*100
randomArray

array([ 135.31702964,   44.35332204, -218.05223145])

In [7]:
data = np.random.randn(2,3)
data

array([[-1.50023546,  0.68818169,  0.28017915],
       [-0.62813117,  0.20534344, -0.22199425]])

In [6]:
randomArray.ndim

1

In [8]:
data.ndim

2

In [9]:
data*10

array([[-15.00235456,   6.88181695,   2.80179146],
       [ -6.2813117 ,   2.05343437,  -2.21994247]])

In [10]:
data+data

array([[-3.00047091,  1.37636339,  0.56035829],
       [-1.25626234,  0.41068687, -0.44398849]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
randomArray.shape

(3,)

In [14]:
randomArray.dtype

dtype('float64')

In [16]:
twoD = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
twoD

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [17]:
twoD.shape
twoD.ndim

2

In [18]:
twoD.shape

(4, 3)

In [19]:
twoD.dtype

dtype('int32')

In [20]:
zeroD = np.array(100)

In [21]:
zeroD

array(100)

In [22]:
zeroD.ndim

0

In [23]:
zeroD.shape

()

In [24]:
miscD = np.array([[[[99]]]])
print(miscD)
print(miscD.shape)
print(miscD.ndim)

[[[[99]]]]
(1, 1, 1, 1)
4


In [25]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
a.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [31]:
flat = np.ravel(a)

In [32]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
flat.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
z = np.array([22,33,44,55,66,77,88,99])
z

array([22, 33, 44, 55, 66, 77, 88, 99])

In [36]:
z.reshape(4,2)

array([[22, 33],
       [44, 55],
       [66, 77],
       [88, 99]])

In [37]:
fz = np.ravel(z)

In [38]:
fz

array([22, 33, 44, 55, 66, 77, 88, 99])

In [39]:
twoD = np.arange(36)
twoD

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
twoD.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [41]:
threeD = twoD.reshape(3,3,4)
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [42]:
threeD.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [43]:
threeD = np.array([[[1,2,3],[2,3,4],[3,4,5],[4,5,6],[5,6,7]]])
threeD

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]]])

In [44]:
twoD + twoD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70])

In [46]:
twoD.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
twoD+twoD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70])

In [48]:
twoD-twoD

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
(twoD/twoD).reshape(6,6)

D:\Users\USER\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [52]:
twoD * twoD

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225])

In [53]:
m1 = np.arange(12).reshape(4,3)

In [54]:
m2 = np.random.randn(16).reshape(4,4)

In [55]:
m1+m2

ValueError: operands could not be broadcast together with shapes (4,3) (4,4) 

In [56]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [57]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Multiplication in matrix:

In [58]:
m1@m3

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [59]:
np.dot(m1,m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [5]:
import numpy as np
m1 = np.arange(12).reshape(4,3)
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
m3 = np.arange(18).reshape(3,6)
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [7]:
m1.dot(m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [9]:
zeeros = np.zeros(4, dtype="int8")
zeeros

array([0, 0, 0, 0], dtype=int8)

In [10]:
print(zeeros.ndim)
print(zeeros.shape)
print(zeeros.dtype)

1
(4,)
int8


In [11]:
zeeros = np.zeros((4,5), dtype="int8")
zeeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [12]:
oness = np.ones((5,5))

In [13]:
oness

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
oness*50

array([[50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.],
       [50., 50., 50., 50., 50.]])

In [15]:
fulll = np.full((4,4),100)

In [16]:
fulll

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [17]:
emptyy = np.empty((4,4,4))
emptyy

array([[[7.42813976e-307, 5.79304851e-312, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+0

In [18]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [19]:
like = np.zeros_like(m3)
like

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [21]:
i = np.eye(5,5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Changing data type:

In [22]:
j = i.astype("int")

In [23]:
j

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Basic Indexing and Slicing:

In [25]:
aList = [3,4,5,6,7]
type(aList[0:3])

list

### Two Dimentional Array:

In [27]:
twoDarray = np.arange(36).reshape(6,6)
twoDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

### Two Dimentional Array indexing:

In [28]:
twoDarray[3,2] #first method

20

In [29]:
twoDarray[3][2] #second method

20

### Two Dimentional Array slicing:

In [31]:
#tDarray[row,column]
#tDarray[start:end, start:end]
twoDarray[2:5,1:3]

array([[13, 14],
       [19, 20],
       [25, 26]])

In [33]:
twoDarray[5:,3:4]

array([[33]])

In [35]:
twoDarray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [37]:
twoDarray[1:2,2:5]

array([[ 8,  9, 10]])

### Three Dimentional Array slicing and indexing:

In [39]:
threeD = np.arange(8).reshape(2,2,2)
threeD

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [42]:
threeD[0][1]

array([2, 3])

In [43]:
threeD[1][1]

array([6, 7])

In [44]:
threeD[1][1][1]

7

In [45]:
threeD[1,1,1] #another method

7

In [47]:
threeD[0, :2] #0 will read 2D

array([[0, 1],
       [2, 3]])

In [51]:
#threeD[twoD index,]
threeD[0, :2,1:]

array([[1],
       [3]])

In [52]:
threeD

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
twoD = np.array([[2,4,6,8,10],[1,2,3,4,5],[4,0,6,2,5],[6,6,1,5,3],[7,5,16,5],[8,2,4,9,7]])
twoD

array([list([2, 4, 6, 8, 10]), list([1, 2, 3, 4, 5]),
       list([4, 0, 6, 2, 5]), list([6, 6, 1, 5, 3]), list([7, 5, 16, 5]),
       list([8, 2, 4, 9, 7])], dtype=object)

In [58]:
arr = np.arange(1,37).reshape(6,6)

In [59]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [57]:
arr[2:4,1:5]

array([[13, 14, 15, 16],
       [19, 20, 21, 22]])

In [63]:
arr[4:5,0:6] #or arr[4] # : means all

array([[25, 26, 27, 28, 29, 30]])

In [64]:
arr[4:5,0:6]
arr[4:5,:]
arr[4:5]
arr[4]

array([25, 26, 27, 28, 29, 30])

In [66]:
arr[:,2]

array([ 3,  9, 15, 21, 27, 33])

In [68]:
arr[1:5,]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [76]:
arr[2:4,5]or  # one vector one dimentional

array([18, 24])

In [79]:
arr[:,::2]

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29],
       [31, 33, 35]])

In [80]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [81]:
arr[:,::-2]

array([[ 6,  4,  2],
       [12, 10,  8],
       [18, 16, 14],
       [24, 22, 20],
       [30, 28, 26],
       [36, 34, 32]])

In [83]:
arr[::2,::2]

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [84]:
arr[0:4:2,::2]

array([[ 1,  3,  5],
       [13, 15, 17]])